In [67]:
import numpy as np


lst = []
  
n = int(input("Enter number of elements : "))
  
for i in range(0, n):
    ele = int(input())
  
    lst.append(ele) 
      
print(lst)

def calculate(lst): 
    if len(lst) < 9:
        raise ValueError("List must contain nine numbers.")
    else:
        lst=np.array(lst)
        lst=lst.reshape(3,3)
    
        lst_flat=lst.flatten()


        lst_mean_1=list(lst.mean(axis=0))
        lst_mean_2=list(lst.mean(axis=1))
        lst_mean_flat=lst_flat.mean()
        mean_summary=lst_mean_1, lst_mean_2, lst_mean_flat

        lst_sum_1=list(lst.sum(axis=0))
        lst_sum_2=list(lst.sum(axis=1))
        lst_sum_flat=lst_flat.sum()
        sum_summary=lst_sum_1, lst_sum_2, lst_sum_flat

        lst_var_1=list(lst.var(axis=0))
        lst_var_2=list(lst.var(axis=1))
        lst_var_flat=lst_flat.var()
        var_summary=lst_var_1, lst_var_2, lst_var_flat

        lst_std_1=list(lst.std(axis=0))
        lst_std_2=list(lst.std(axis=1))
        lst_std_flat=lst_flat.std()
        std_summary=lst_std_1, lst_std_2, lst_std_flat

        lst_min_1=list(lst.min(axis=0))
        lst_min_2=list(lst.min(axis=1))
        lst_min_flat=lst_flat.min()
        min_summary=lst_min_1, lst_min_2, lst_min_flat

        lst_max_1=list(lst.max(axis=0))
        lst_max_2=list(lst.max(axis=1))
        lst_max_flat= lst_flat.max()
        max_summary=lst_max_1, lst_max_2, lst_max_flat
        
        summary_stat={
              'Mean': mean_summary, 
              'Variance': var_summary,
              'Standard deviation': std_summary,
              'Max': max_summary,
              'Min': min_summary,
              'Sum': sum_summary
        }
        print(lst)
        print(summary_stat)

calculate(lst)







    
    
    

    



Enter number of elements : 9
1
2
3
4
5
6
7
8
9
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
{'Mean': ([4.0, 5.0, 6.0], [2.0, 5.0, 8.0], 5.0), 'Variance': ([6.0, 6.0, 6.0], [0.6666666666666666, 0.6666666666666666, 0.6666666666666666], 6.666666666666667), 'Standard deviation': ([2.449489742783178, 2.449489742783178, 2.449489742783178], [0.816496580927726, 0.816496580927726, 0.816496580927726], 2.581988897471611), 'Max': ([7, 8, 9], [3, 6, 9], 9), 'Min': ([1, 2, 3], [1, 4, 7], 1), 'Sum': ([12, 15, 18], [6, 15, 24], 45)}
